project_id = "wberoibxqpffhnyvjnci"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.generate-ticket-pdf]
verify_jwt = false

[functions.lookup-booking]
verify_jwt = false

[functions.generate-tour-documents]
verify_jwt = false
