// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-package-tours.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function serviceClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_package_tours_default = defineTool({
  name: "list_package_tours",
  title: "List package tours",
  description: "List active METROPOL TOURS package tours (Pauschalreisen) with title, destination, price and slug.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of tours to return (default 20)."),
    search: z.string().optional().describe("Case-insensitive substring to filter tour titles.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ limit, search }) => {
    const supabase = serviceClient();
    let query = supabase.from("package_tours").select("id, title, slug, destination, base_price, duration_days, is_active").eq("is_active", true).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tours: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/lookup-booking.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var lookup_booking_default = defineTool2({
  name: "lookup_my_booking",
  title: "Look up my booking",
  description: "Look up a booking for the signed-in user by ticket number (TKT-YYYY-######). Returns booking status, passenger name and trip info.",
  inputSchema: {
    ticket_number: z2.string().trim().min(3).describe("Ticket number, e.g. TKT-2026-000123.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ ticket_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").select(
      "id, ticket_number, status, passenger_first_name, passenger_last_name, price_paid, created_at, trip_id"
    ).eq("ticket_number", ticket_number).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [
          { type: "text", text: `No booking found for ${ticket_number}.` }
        ]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wberoibxqpffhnyvjnci";
var mcp_default = defineMcp({
  name: "metropol-tours-mcp",
  title: "METROPOL TOURS MCP",
  version: "0.1.0",
  instructions: "Tools for METROPOL TOURS. Use `list_package_tours` to browse active package tours (Pauschalreisen). Use `lookup_my_booking` (requires sign-in) to look up a booking by its TKT-YYYY-###### ticket number for the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_package_tours_default, lookup_booking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
